import os
os.system('yum -y remove hadoop-*')
os.system('yum -y remove hive*')
os.system('yum -y remove pig-udf-datafu')
os.system('yum -y remove tez')
os.system('yum -y remove ranger-*')
os.system('yum -y remove hbase')
os.system('yum -y remove phoenix')
os.system('yum -y remove mahout')
os.system('yum -y remove zookeeper')
os.system('yum -y remove kafka')
os.system('yum -y remove kafka-server')
os.system('yum -y remove spark-*')
os.system('yum -y remove solr')
os.system('rm -rf /usr/lib/hadoop-*')
os.system('rm -rf /usr/lib/hive*')
os.system('rm -rf /usr/lib/hbase')
os.system('rm -rf /usr/lib/phoenix')
os.system('rm -rf /usr/lib/zookeeper')
os.system('rm -rf /etc/hadoop')
os.system('rm -rf /etc/hive*')
os.system('rm -rf /etc/hbase')
os.system('rm -rf /etc/phoenix')
os.system('rm -rf /etc/zookeeper')
